### ISSUE TITLE
Pluralization is displaying "zero" instead of "one"

### ISSUE THREAD

**Issue by hanwu85** [jonatanklosko/internationalize#12]
I have noticed that all the pluralization display of "one" is displayed as "zero" in the input area.
I don't know if this has been reported before.
![image](https://user-images.githubusercontent.com/3752812/64918052-c2560780-d7d3-11e9-892e-0dba62688210.png)

Thank you!

**Comment by jonatanklosko** [comment]
Pluralized keys are handled a bit differently as languages differ on that (some have just singular/plural form, others use different wording for one/few/many, etc.). So each language gets its own set of pluralization scenarios to translate. In your case it's just that for English we have `one` and `other` keys, whereas for Taiwanese we only have `other` (but the app also enforces `zero` for every language, as you sometimes would write something specific like "none" instead of "0 items").

Please, let me know if anything is not clear =)

**Comment by hanwu85** [comment]
Thank you for clearing that up.  So it means I will ignore the one in the EN and treat the zero as zero, and the "one" is included in the "other".  Am I correct?

**Comment by jonatanklosko** [comment]
Yeah, `one` is not relevant in your case. In your language when `count` is 0 the translation `zero` will be displayed and `other` otherwise.
